# Generated by Django 5.0.7 on 2024-07-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="image",
            name="external_id",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
