# Generated by Django 5.0.7 on 2024-07-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_message_options_image_external_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("created_at",)},
        ),
        migrations.AlterField(
            model_name="chat",
            name="messages",
            field=models.ManyToManyField(related_name="chats", to="chat.message"),
        ),
        migrations.AlterField(
            model_name="image",
            name="external_id",
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.CharField(max_length=1024),
        ),
    ]
